Perfect! Here’s a compact, interview-ready cheat table for Node.js reliability & fault tolerance (2026) with layers, patterns, tools, and real-world examples:

| Layer / Concern                 | Fault Scenario                                   | Node.js Patterns / Tools                                                         | Real-World Example / Notes                                                                     |
| ------------------------------- | ------------------------------------------------ | -------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| **Process / Instance**          | Single Node process crashes                      | PM2 (cluster mode), Node.js `cluster`, auto-restart                              | Worker dies → PM2 restarts it; multi-core CPU utilization; basic availability.                 |
| **Resilience / External Calls** | API/DB failures, slow responses                  | Circuit breaker (`opossum`), Retries (`Polly.js` / `undici`), `AbortController`  | Payment API fails → circuit trips; retry transient errors; timeout slow requests.              |
| **Scaling / Redundancy**        | Instance or machine unavailable                  | Load balancer (Nginx, HAProxy, AWS ALB), Horizontal scaling                      | Node.js API instances behind LB; traffic rerouted to healthy pods/servers.                     |
| **State / Coordination**        | In-memory data lost, session/state inconsistency | Redis (replication, pub/sub, sessions), Database replication (MongoDB, Postgres) | Redis cluster ensures session and pub/sub survives process crashes.                            |
| **Advanced Fault Tolerance**    | Long-running workflows crash                     | Temporal.io (sagas/workflows), Moleculer / NestJS microservices                  | Payment saga survives crashes; jobs resume automatically; ensures eventual consistency.        |
| **Observability / Detection**   | Failures unnoticed                               | Prometheus + Grafana, Datadog, New Relic, Logs + Alerts                          | Detect error spikes, high latency, circuit breaker trips; prevent user-visible downtime.       |
| **Deployment / Platform**       | Pod / server / zone failure                      | Kubernetes (auto-healing, rolling updates, multi-zone), Docker                   | Failed pod replaced automatically; rolling update avoids downtime; survive data center outage. |
