| Layer / Concern                   | What-If Scenario / Question         | Node.js Patterns / Tools                                                                                                              | Real-World Example / Notes                                                                                         |
| --------------------------------- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------ |
| **Process / Instance**            | Node.js process crashes             | PM2 (cluster mode), Node.js `cluster`, auto-restart                                                                                   | Worker dies → PM2 restarts automatically. Multi-core CPU utilization, basic availability.                          |
| **Resilience / External Calls**   | API or DB fails                     | Circuit breaker (`opossum`), retries (`Polly.js` / `undici`), `AbortController`                                                       | Prevent cascading failures; retry transient errors; abort slow calls.                                              |
| **Scaling / Overload**            | Traffic spikes                      | Load balancer (Nginx, HAProxy, AWS ALB), multiple Node.js instances, PM2 cluster, queueing (Bull, Kafka), rate-limiting               | Requests distributed → avoids CPU saturation. Long tasks offloaded to queues. Rate-limit abusive clients.          |
| **Caching / Performance**         | Slow responses / high latency       | Redis / Memcached, CDN (CloudFront, Fastly), precomputing, DB indexes, compression                                                    | Session data, product catalogs in Redis; static assets on CDN; precomputed analytics → fast response.              |
| **State / Coordination**          | In-memory state lost                | Redis (replication, pub/sub, session store), DB replication (MongoDB/Postgres)                                                        | Node.js instances remain stateless. Redis cluster ensures shared state survives crashes.                           |
| **Consistency / Data Integrity**  | Data incorrect / concurrent updates | ACID transactions, distributed locks (`redlock`), saga pattern (Temporal.io), idempotency keys, schema validation (Joi/Zod, Mongoose) | Payment transfers, inventory updates, workflows → either fully succeed or rollback; safe retries avoid duplicates. |
| **Advanced Fault Tolerance**      | Long-running workflows crash        | Temporal.io, Moleculer / NestJS microservices                                                                                         | Workflows survive instance crashes; compensating actions applied for failed steps.                                 |
| **Observability / Detection**     | Failures unnoticed                  | Prometheus + Grafana, Datadog, New Relic, centralized logging                                                                         | Monitor latency, error spikes, circuit breaker trips; alerts → early detection before user impact.                 |
| **Deployment / Platform**         | Pod / server / zone fails           | Kubernetes (auto-healing, rolling updates, multi-zone), Docker                                                                        | Failed pods replaced automatically; zero-downtime rolling updates; survive data center outages.                    |
| **Input / Request Validation**    | Bad data enters system              | Joi / Zod schemas, Mongoose / TypeORM schemas                                                                                         | Ensure incoming requests are correct → reduces invalid DB writes and runtime errors.                               |
| **Event-Driven / Async Handling** | Loose coupling / async tasks        | EventEmitter, pub/sub (Redis / Kafka), async wrappers / HOF (`asyncHandler`)                                                          | Decouple producers & consumers; centralized async error handling in controllers.                                   |
| **Adapter / Integration**         | Third-party APIs incompatible       | Adapter pattern (wrap SDKs), API gateways                                                                                             | Stripe, Twilio, legacy service integration → uniform internal interface.                                           |
